<a href="https://colab.research.google.com/github/yogeshmotwani1/proj1/blob/master/preprocess_for_twint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Query in Twint API for fetching all the tweets having rblbankcares in any parmater from yesterday 8pm to today 10am**

$ twint -s rblbankcares --since "2020-08-12 20:00:00" -o file.csv --csv

In [4]:
import pandas as pd
import re
import string
import nltk
import regex
nltk.download('words')
nltk.download('punkt')

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [6]:
df = pd.read_csv('file.csv')

In [ ]:
df.head()

                User  ...                                             Review
0     jobanpreet1313  ...  The oneplus nord is one of those phone that do...
1  adarshsinghsengar  ...  1) Premium design2) 6.44-inch display, 20:9 as...
2  divyanshkumardk20  ...  This is the best phone of one plus under 25k t...
3    chandwanianupam  ...  THE NORD IS A FINE OVERALL PACKAGE BUT DO NOT ...
4      dharaaapatel1  ...  Best Phone Until Now By Oneplus ??I mean the b...

[5 rows x 4 columns]

In [ ]:
df = df.loc[df['username']!='rblbankcares']

In [ ]:
df = df.drop_duplicates(subset=['username'] ,keep="last")

In [ ]:
df['tweet']

0     Thanks for quick reply on twitter. Contact has...
2     @PoliceRajasthan @jaipur_police Please HELP SO...
4     @rblbank @RBLBankCares what the hell??\nno res...
5     @rblbank @RBLBankCares मेरे एकाउंट पर 3 हजार क...
6     @rblbank @RBLBankCares @RBI yet see a revert i...
8     @RBLBankCares @DCP grugram@pmo india @rbi I ha...
13                                        @RBLBankCares
14    I hope this time your representative has knowl...
17    @rblbank @RBLBankCares -- Yesterday there was ...
19    Hi sir good morning\nMy self Brijesh Kumar pat...
23    If one bank employee abuse by person top minis...
26    Credit card recovery agents are second most he...
27                                        @rblbank @RBI
28                                         #moratorium3
29    @rblbank @RBLBankCares from last 4 month I'm t...
32    @RBLBankCares\n@rblbank\nI have an credit card...
34    @RBLBankCares @rblbank @RBI @PMOIndia @nsithar...
35    @RBLBankCares @rblbank @vishwavirahuja\nIt's c...
36    See this image and investigation fastly pic.tw...
37    @RBI @RBLBankCares @rblbank please help https:...
38    No response yet plz resolve my problem\n\nRega...
39        No one called!!! So you guys need only Money.
40    @RBLBankCares your application for credit card...
41    @rblbank @RBLBankCares\nCREDIT CARD - 5243-736...
42    @RBLBankCares I have not received credit card ...
43    Still i did not get any call or email from you...
44    @RBLBankCares can you help me with this , my c...
46    @RBLBankCares @rblbank I think you people are ...
47    Don't give me false commitment if you don't ha...
55                 Done already before sharing on tweet
56    @RBLBankCares @rblbank\n I hv taken moratorium...
57    @RBLBankCares pls let me know the interest cha...
58    @RBLBankCares So I talked to your company guy ...
59    @RBLBankCares no one answering my queries...I ...
62    @MoneyTapApp  no reply after long wait, very p...
63    @RBLBankCares unable to login and create accou...
67    Worst collection department operated is by @RB...
68    @rblbank any updates? For u guys customers are...
70    .@RBI May I get any help as @rblbank @RBLBankC...
73    Your representative will never get in touch an...
74    @RBLBankCares\n@rblbank\n@SBICard_Connect\n@TV...
76    @RBLBankCares @rblbank \nPlease help, fraudule...
79    @RBLBankCares  5 times on each day) and then f...
Name: tweet, dtype: object

In [ ]:
def cleanTxt(text):
    text = text.lower()
    text = re.sub('@[A-Za-z0–9_]+', '', text) #Removing @mentions
    text = re.sub('#', '', text) # Removing '#' hash tag
    text = re.sub('RT[\s]+', '', text) # Removing RT
    text = re.sub('https?:\/\/\S+', '', text) # Removing hyperlink
    text = re.sub('\n','',text) # Removing newline characters
    text = re.sub('\[.*?\]', '', text) # Removing text in brackets
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text) # Removing punctuations
    text = re.sub('\w*\d\w*', '', text) # Removing letters

 
    return text

df['tweet'] = df['tweet'].apply(cleanTxt)

In [ ]:
df['tweet'].head()

0    thanks for quick reply on twitter contact has ...
2      please help sos rbl bank goons are threateni...
4      what the hellno response why you dont cancel...
5      मेरे एकाउंट पर  हजार का मेम्बरशिप फीस का चार...
6       yet see a revert in thisyou guys can call c...
Name: tweet, dtype: object

In [ ]:
def remove_non_english(text):
    words = set(nltk.corpus.words.words())
    sent = text
    sent = " ".join(w for w in nltk.word_tokenize(sent) if w.lower() in words or not w.isalpha())
    return sent

df['tweet'] = df['tweet'].apply(remove_non_english)

In [ ]:
def remove_hindi_tweets(text):
    mystring = text
    words = mystring.split(" ")
    for word in words:
        if regex.match('[\u0900-\u097F]+', word):
            return ""
    return mystring
df['tweet'] = df['tweet'].apply(remove_hindi_tweets)

In [ ]:
df = df.loc[df['tweet']!='']

In [ ]:
df.reset_index()

    index                   id  ...  trans_src  trans_dest
0       0  1293768548934774785  ...        NaN         NaN
1       2  1293767615819558913  ...        NaN         NaN
2       4  1293765485054418945  ...        NaN         NaN
3       6  1293765196784078849  ...        NaN         NaN
4       8  1293765077137371136  ...        NaN         NaN
5      14  1293754897901293569  ...        NaN         NaN
6      17  1293753190475653120  ...        NaN         NaN
7      19  1293752365309280256  ...        NaN         NaN
8      23  1293747990927036417  ...        NaN         NaN
9      26  1293745567869222915  ...        NaN         NaN
10     29  1293744688428535808  ...        NaN         NaN
11     32  1293742248807378944  ...        NaN         NaN
12     34  1293736067506438144  ...        NaN         NaN
13     35  1293727631741861890  ...        NaN         NaN
14     36  1293720135304273920  ...        NaN         NaN
15     37  1293719018788986882  ...        NaN         NaN
16     38  1293718254523781122  ...        NaN         NaN
17     39  1293657605487779841  ...        NaN         NaN
18     40  1293652457529073664  ...        NaN         NaN
19     41  1293633864523345921  ...        NaN         NaN
20     42  1293631715798159361  ...        NaN         NaN
21     43  1293626499744980992  ...        NaN         NaN
22     44  1293618748461477888  ...        NaN         NaN
23     46  1293612122601975808  ...        NaN         NaN
24     47  1293609452076072960  ...        NaN         NaN
25     55  1293601756450918400  ...        NaN         NaN
26     56  1293600860115570689  ...        NaN         NaN
27     57  1293593881662062593  ...        NaN         NaN
28     58  1293592780644614145  ...        NaN         NaN
29     59  1293591784522567680  ...        NaN         NaN
30     62  1293584981999067138  ...        NaN         NaN
31     63  1293581021292531717  ...        NaN         NaN
32     67  1293576053168828421  ...        NaN         NaN
33     68  1293572812100124673  ...        NaN         NaN
34     70  1293570719821885442  ...        NaN         NaN
35     73  1293568578235453440  ...        NaN         NaN
36     74  1293564585748787203  ...        NaN         NaN
37     76  1293562212229865473  ...        NaN         NaN
38     79  1293559095509708800  ...        NaN         NaN

[39 rows x 35 columns]

In [ ]:
df['tweet']

0     thanks for quick reply on twitter contact been...
2     please help bank are threatening me and my fam...
4     what the response why you dont cancel previous...
6     yet see a revert in can call for payment durin...
8     i have take already moratorium but bank agent ...
14    i hope this time your representative knowledge...
17    yesterday there was a fraudulent transaction t...
19    hi sir good self is not i am sending to much m...
23    if one bank employee abuse by person top and w...
26    credit card recovery are second most heart les...
29    from last month trying to contact with custome...
32    i have an credit card of of moratorium then wh...
34    i have the amount by you as per the last bill ...
35    its confirm now that you dont bother about use...
36                     see this image and investigation
37                                        please help …
38    no response yet resolve my health insurance mo...
39                        no one so you need only money
40    your application for credit card been hacked p...
41    credit card and case is mobile no se gali bahu...
42    i have not received credit card yet even after...
43    still i did not get any call or from your serv...
44    can you help me with this my card is being blo...
46                               i think you people are
47       dont give me false commitment if you dont have
55                         done already before on tweet
56    i taken moratorium in on my loan no outstandin...
57          let me know the interest if i convert in to
58    so i to your company guy he said that i will g...
59    no one my am paying the amount check and sent ...
62           no reply after long wait very poor service
63    unable to login and create account for the tel...
67    worst collection department is by not to any l...
68                                   any for u are just
70    may i get any help as is not on query even is ...
73    your representative will never get in touch an...
74    card a very dirty service a wrong bill every t...
76    please help fraudulent transaction of been don...
79    times on each day and then follow up by your s...
Name: tweet, dtype: object